backend:
  name: git-gateway
  branch: master
  repo: daltn/money-cat

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    fields:
      - {
          label: "Slug",
          name: "slug",
          widget: "string",
          hint: "URL safe slug plz",
          pattern:
            [
              "[a-zA-Z0-9_-]",
              "Must have be URL safe. Only letters, numbers, and dashes",
            ],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
